@hostname = localhost
@port = 3333
@host = {{hostname}}:{{port}}
@customerId = 1e567e50-4dee-487b-bf70-27a9f45ca002
@customerEmailSufix = {{$randomInt 1 1000}}
@productIdA = 2e567e50-4dee-487b-bf70-27a9f45ca003
@productIdB = 2e567e50-4dee-487b-bf70-27a9f45ca004
@productCodeSufix = {{$randomInt 1 1000}}

###

# @name purchase-create-customer

POST http://{{host}}/customer
Content-Type: application/json

{
  "id": "{{customerId}}",
  "name": "Leandro Fernandes",
  "email": "leo{{customerEmailSufix}}@gmail.com",
  "password": "123456",
  "phone": "(99)99999-9999"
}

###

# @name purchase-create-customer-random

POST http://{{host}}/customer
Content-Type: application/json

{
  "id": "{{$guid}}",
  "name": "Leandro Fernandes",
  "email": "leo{{customerEmailSufix}}@gmail.com",
  "password": "123456",
  "phone": "(99)99999-9999"
}

###

# @name purchase-create-product-1

POST http://{{host}}/product
Content-Type: application/json

{
  "id": "{{productIdA}}",
  "code": "P{{productCodeSufix}}",
  "description": "Produto de teste {{productCodeSufix}}",
  "salePrice": 50.00,
  "stock": 25
}

###

# @name purchase-create-product-2

POST http://{{host}}/product
Content-Type: application/json

{
  "id": "{{productIdB}}",
  "code": "P{{productCodeSufix}}",
  "description": "Produto de teste {{productCodeSufix}}",
  "salePrice": 50.00,
  "stock": 25
}

###

# @name purchase-create-product-random

POST http://{{host}}/product
Content-Type: application/json

{
  "id": "{{$guid}}",
  "code": "P{{productCodeSufix}}",
  "description": "Produto de teste {{productCodeSufix}}",
  "salePrice": 50.00,
  "stock": 25
}

###

# @name purchase-create-purchase

POST http://{{host}}/purchase
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "value": 250.00,
  "items": [{
    "productId": "{{productIdA}}",
    "quantity": 2,
    "totalValue": 100
  },
  {
    "productId": "{{productIdB}}",
    "quantity": 1,
    "totalValue": 50
  }]
}